[project]
name = 'Decentralized-Academic-Research-Funding'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.milestone-funding-manager]
path = 'contracts/milestone-funding-manager.clar'
clarity_version = 3
epoch = 'latest'

[contracts.peer-review-coordinator]
path = 'contracts/peer-review-coordinator.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
